### ISSUE TITLE
A crash when parsing module YAML file for firefox-flatpak-9020020230217074331.9bc4ec6c RHEL build

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#1093]
Latest git code as well as rpminspect-1.11-0.1.202302170726gitdd03fc8.el9.x86_64 crashes like this when parsing YAML document for a firefox-flatpak-9020020230217074331.9bc4ec6c RHEL module build:

~~~~
$ /tmp/build/src/rpminspect -c /usr/share/rpminspect/redhat.yaml --debug --verbose --arches=x86_64 --keep --build-type=module --tests=modularity --format=summary firefox-flatpak-9020020230217074331.9bc4ec6c
Downloading module firefox-flatpak-9020020230217074331.9bc4ec6c
debug: curl_get_file (169): src=|https://download.devel.redhat.com/brewroot/packages/firefox/flatpak/9020020230217074331.9bc4ec6c/files/module/modulemd.txt|
dst=|/var/tmp/rpminspect/firefox-flatpak.lIwCPW/after/files/modulemd.txt|
=> modulemd.txt                                                                                        [#######################################################################################################]
Segmentation fault (core dumped)
~~~~

A debugger shows:

~~~~
Thread 1 "rpminspect" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f5e1c3 in y_free_tree (v=0x521180) at ../rpminspect/lib/parse_yaml.c:374
374             for (i = 0; v->v.dict.keys[i] != NULL; i++) {
(gdb) p *v
$1 = {type = Y_DICT, v = {string = 0x0, array = 0x0, dict = {keys = 0x0, values = 0x0}}}
(gdb) bt
#0  0x00007ffff7f5e1c3 in y_free_tree (v=0x521180) at ../rpminspect/lib/parse_yaml.c:374
#1  0x00007ffff7f5e1e3 in y_free_tree (v=0x4c3e20) at ../rpminspect/lib/parse_yaml.c:376
#2  0x00007ffff7f5e1e3 in y_free_tree (v=0x4963d0) at ../rpminspect/lib/parse_yaml.c:376
#3  0x00007ffff7f5e1e3 in y_free_tree (v=0x591160) at ../rpminspect/lib/parse_yaml.c:376
#4  0x00007ffff7f24004 in download_build (ri=ri@entry=0x43f300, build=build@entry=0x5f6b40) at ../rpminspect/lib/builds.c:390
#5  0x00007ffff7f24c7e in _gather_build_types (ri=ri@entry=0x43f300) at ../rpminspect/lib/builds.c:897
#6  0x00007ffff7f2596b in gather_builds (ri=ri@entry=0x43f300, fo=fo@entry=false) at ../rpminspect/lib/builds.c:946
#7  0x00000000004033d4 in main (argc=11, argv=<optimized out>) at ../rpminspect/src/rpminspect.c:825
~~~~

It's a crash in lib/parse_yaml.c:y_free_tree() when deallocating y_value structure. Called from download_build() at the end of successful "Get the list of artifacts to filter if we don't have it" block.

**Comment by ppisar** [comment]
This seems to be triggered by this pice of YAML:

~~~~
  buildopts:
    rpms: {}
    arches: [x86_64]
~~~~

rpms value is an empty mapping, hence the rpms' value is of type Y_DICT and v.dict.keys as well as v.dict.values are NULL. The destructor function does not expect a dict value without allocated key and value arrays. Either the destructor should be more robust or a constructor should allocate keys and values, albeit {NULL} ones.

Modulemd specification marks all buildopts keys optional. So it's a valid input.
