### ISSUE TITLE
rpminspect dies with "double free detected in tcache 2"

### ISSUE THREAD

**Issue by happz** [rpminspect/rpminspect#186]
```
Running %files inspection...         pass
Running types inspection...          FAIL
free(): double free detected in tcache 2

Thread 1 "rpminspect" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50        return ret;
Missing separate debuginfos, use: dnf debuginfo-install json-c-0.13.1-12.fc31.x86_64 libacl-2.2.53-4.fc31.x86_64 libarchive-3.4.2-1.fc31.x86_64 libidn2-2.3.0-1.fc31.x86_64 libnghttp2-1.40.0-1.fc31.x86_64 libpsl-0.21.0-2.fc31.x86_64 libssh-0.9.4-2.fc31.x86_64 pcre2-10.35-4.fc31.x86_64
(gdb) 
(gdb) 
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7d148d9 in __GI_abort () at abort.c:79
#2  0x00007ffff7d6f4bf in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7e7ef4b "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff7d76aac in malloc_printerr (str=str@entry=0x7ffff7e80b40 "free(): double free detected in tcache 2") at malloc.c:5339
#4  0x00007ffff7d788fd in _int_free (av=0x7ffff7eb19e0 <main_arena>, p=0x555555bfa080, have_lock=0) at malloc.c:4201
#5  0x00007ffff7f527a2 in get_abi_dir_arg (ri=ri@entry=0x555555561580, size=size@entry=2, suffix=suffix@entry=0x7ffff7f9baa2 "-debuginfo", 
    arg=arg@entry=0x7ffff7f9bd55 "--debug-info-dir1", path=path@entry=0x7ffff7f98ab5 "/usr/lib/debug/", type=type@entry=0) at ../lib/abi.c:476
#6  0x00007ffff7f5ece9 in inspect_abidiff (ri=0x555555561580) at ../lib/inspect_abidiff.c:339
#7  0x0000555555557889 in main (argc=<optimized out>, argv=<optimized out>) at ../src/rpminspect.c:785
(gdb) 
```

```
(gdb) up
#5  0x00007ffff7f527a2 in get_abi_dir_arg (ri=ri@entry=0x555555561580, size=size@entry=2, suffix=suffix@entry=0x7ffff7f9baa2 "-debuginfo", 
    arg=arg@entry=0x7ffff7f9bd55 "--debug-info-dir1", path=path@entry=0x7ffff7f98ab5 "/usr/lib/debug/", type=type@entry=0) at ../lib/abi.c:476
476                 free(tmp);
(gdb) list
471                 }
472             }
473
474             if (tmp) {
475                 add_abi_argument(table, arg, tmp, h);
476                 free(tmp);
477             }
478         }
479
480         return table;
(gdb) 

```

```
/usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml -v -w tmpzwzHzp/artifacts -o tmpzwzHzp/rpminspect-results.txt -F json -T ALL dotnet-2.1.513-2.el8 dotnet-2.1.514-1.el8_2
```

```
librpminspect-1.1-0.1.202008191616git.fc31.x86_64
librpminspect-debuginfo-1.1-0.1.202008191616git.fc31.x86_64
rpminspect-1.1-0.1.202008191616git.fc31.x86_64
rpminspect-data-redhat-1.1-0.1.202008191616git.fc31.noarch
rpminspect-debuginfo-1.1-0.1.202008191616git.fc31.x86_64
rpminspect-debugsource-1.1-0.1.202008191616git.fc31.x86_64
```

**Comment by dcantrell** [comment]
Thanks for the report.  I've fixed the problem and a patch is coming momentarily.  Right now librpminspect is leaking about 2 Kb and I want to clean that up too.  It's all in the same code path.

The reason you ran in to this bug is those dotnet packages lacked debuginfo packages that rpminspect could download.  So when it was collecting debuginfo paths for the abidiff inspection, it was not properly handling instances where the debuginfo package was not available.  This is a good find because koji sometimes just doesn't have those for builds, so we need to account for those use cases.
