### ISSUE TITLE
Segfault in inspect_abidiff

### ISSUE THREAD

**Issue by happz** [rpminspect/rpminspect#244]
```
$ /usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml -v -w tmp7BzFbX/artifacts -o tmp7BzFbX/rpminspect-results.txt -F json -T ALL flex-2.5.37-3.el7 flex-2.5.37-6.el7
```

```
...
Running annocheck inspection...      pass
Running dsodeps inspection...        FAIL
Running filesize inspection...       pass
Running permissions inspection...    pass
Running capabilities inspection...   pass
Running kmod inspection...           pass
Running arch inspection...           pass
Running subpackages inspection...    pass
Running changelog inspection...      pass
Running pathmigration inspection...  pass
Running lto inspection...            pass
Running symlinks inspection...       pass
Running files inspection...          pass
Running types inspection...          pass

Thread 1 "rpminspect" received signal SIGBUS, Bus error.
list_free (free_func=<optimized out>, list=<optimized out>) at ../lib/listfuncs.c:356
356             TAILQ_REMOVE(list, entry, items);
Missing separate debuginfos, use: dnf debuginfo-install json-c-0.13.1-12.fc31.x86_64 libacl-2.2.53-4.fc31.x86_64 libarchive-3.4.2-1.fc31.x86_64 libcap-ng-0.7.10-1.fc31.x86_64 libffi-3.1-23.fc31.x86_64 libidn2-2.3.0-1.fc31.x86_64 libnghttp2-1.40.0-1.fc31.x86_64 libpsl-0.21.0-2.fc31.x86_64 libssh-0.9.4-2.fc31.x86_64 nettle-3.5.1-3.fc31.x86_64 p11-kit-0.23.20-1.fc31.x86_64
(gdb) bt
#0  list_free (free_func=<optimized out>, list=<optimized out>) at ../lib/listfuncs.c:356
#1  list_free (list=0x55555555d010, free_func=0x7ffff7d737a0 <free>) at ../lib/listfuncs.c:346
#2  0x00007ffff7f4b954 in free_abi (list=0x555555948820) at ../lib/abi.c:357
#3  0x00007ffff7f5968f in inspect_abidiff (ri=0x55555557d4e0) at ../lib/inspect_abidiff.c:372
#4  0x00005555555578d3 in main (argc=<optimized out>, argv=<optimized out>) at ../src/rpminspect.c:794
(gdb) 
```

```
librpminspect-1.2-0.1.202010152017git.fc31.x86_64
rpminspect-1.2-0.1.202010152017git.fc31.x86_64
rpminspect-data-redhat-1.2-0.1.202010072009git.fc31.noarch
```

This is a regression, this exact command line used to work with this version:

```
librpminspect-1.2-0.1.202009231440git.fc31.x86_64
rpminspect-1.2-0.1.202009231440git.fc31.x86_64
rpminspect-data-redhat-1.1-0.1.202009171820git.fc31.noarch
```

**Comment by dcantrell** [comment]
Working on this now.  Thanks for the clear bug report with the reproducer.

**Comment by dcantrell** [comment]
Oh, I actually saw this over the weekend while I was working on rpminspect and am in the middle of a fix.  Should have this finished momentarily.

**Comment by dcantrell** [comment]
Fix pushed.
