### ISSUE TITLE
Patches section breaks json parsing

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#245]
Hello
We use python json parser to parse rpminspect results, but lately we have weird unparsable messages in the patches section. It breaks json parser and our CI in general. In my opinion messages always should have utf-8 encoding

Note that is not the latest version of packages, I can't reproduce the problem because of the https://github.com/rpminspect/rpminspect/issues/244
```
$ rpminspect -c /usr/share/rpminspect/redhat.yaml -v  -F json servicemesh-operator-1.1.10-1.el8 servicemesh-operator-2.0.0-2.el8
...
   "patches": [
     {
       "result": "INFO",
       "waiver authorization": "Not Waivable",
       "message": "Patch file `0001-MAISTRA-1464-Update-gopkg.in-yaml.v2-to-v2.3.0.patch` removed"
     },
     {
       "result": "INFO",
       "waiver authorization": "Not Waivable",
       "message": "Patch file `istio-operator-7ac6f2643bf7de61acf6c7d914de6c4046c4d97f.tar.gz` removed"
     },
     {
       "result": "OK",
       "waiver authorization": "Not Waivable",
       "message": "@~}��U"
     }
   ],
...
```
More reproducers:
```
$ rpminspect -c /usr/share/rpminspect/redhat.yaml -v  -F json kubevirt-0.30.6-52.el7 kubevirt-2.5.0-87.el7
$ rpminspect -c /usr/share/rpminspect/redhat.yaml -v  -F json ansible-tower-3.7.3-1.el7at ansible-tower-3.7.3-1.el7at
```
* rpminspect-1.2-0.1.202010140231git.fc31.x86_64
* librpminspect-1.2-0.1.202010140231git.fc31.x86_64
* rpminspect-data-redhat-1.2-0.1.202010072009git.fc31.noarch

**Comment by ukulekek** [comment]
How to test:
* Add `-o results` to a rpminspect command
* Run:
```
$ python
Python 2.7.18 (default, Jul 20 2020, 00:00:00) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> f = open('results')
>>> data = json.load(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 4: unexpected end of data
```

**Comment by dcantrell** [comment]
This is a result of me handing libjson-c a NULL pointer, so the result string is garbage.  I have fixed this up and tested it locally so you should not see it anymore.

I am not opposed to UTF-8 encoding at all, but I would prefer to treat that as a separate RFE.
