### ISSUE TITLE
rpminspect: assertion failure when running on grub2

### ISSUE THREAD

**Issue by frozencemetery** [rpminspect/rpminspect#526]
With rpminspect from git:

```
[root@fedora src]# gdb --args ./rpminspect -c /usr/share/rpminspect/fedora.yaml -kw ~/tmp grub2-2.06-5.fc35

...

rpminspect: ../lib/fileinfo.c:56: match_fileinfo_mode: Assertion `fname != NULL' failed.
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "rpminspect" received signal SIGABRT, Aborted.
__pthread_kill_internal (threadid=<optimized out>, signo=signo@entry=6) at pthread_kill.c:41
41	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_internal (threadid=<optimized out>, signo=signo@entry=6) at pthread_kill.c:41
#1  0x00007ffff7d07861 in __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6)
    at pthread_kill.c:82
#2  0x00007ffff7cba676 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7ca47d3 in __GI_abort () at abort.c:79
#4  0x00007ffff7ca46fb in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, 
    file=<optimized out>, line=<optimized out>, function=<optimized out>) at assert.c:92
#5  0x00007ffff7cb3366 in __GI___assert_fail (assertion=0x7ffff7f986ba "fname != NULL", 
    file=0x7ffff7f98690 "../lib/fileinfo.c", line=56, 
    function=0x7ffff7f98940 <__PRETTY_FUNCTION__.3> "match_fileinfo_mode") at assert.c:101
#6  0x00007ffff7f31537 in match_fileinfo_mode (ri=0x42aee0, file=0x710130, 
    header=0x7ffff7f9cbce "addedfiles", 
    remedy=0x7ffff7f9cbe0 "Unexpected file additions were found.  Verify these changes are correct.  If they are not, adjust the build to prevent the file additions between builds.  If they are correct, update %s and send a pat"..., fname=0x0) at ../lib/fileinfo.c:56
#7  0x00007ffff7f43a62 in addedfiles_driver (ri=0x42aee0, file=0x710130)
    at ../lib/inspect_addedfiles.c:178
#8  0x00007ffff7f41cff in foreach_peer_file (ri=0x42aee0, inspection=0x7ffff7f9cbce "addedfiles", 
    check_fn=0x7ffff7f43216 <addedfiles_driver>, use_ignore=false) at ../lib/inspect.c:129
#9  0x00007ffff7f43baf in inspect_addedfiles (ri=0x42aee0) at ../lib/inspect_addedfiles.c:209
#10 0x0000000000404638 in main (argc=6, argv=0x7fffffffe2a8) at ../src/rpminspect.c:834
(gdb) 

...

(gdb) p *file
$2 = {rpm_header = 0x689b20, 
  fullpath = 0x4b3ca0 "/root/tmp/grub2-2.06.OCwzOw/after/armv7hl/grub2-tools-minimal-2.06-5.fc35.armv7hl//usr/sbin/grub2-set-bootflag", 
  localpath = 0x5ed520 "/usr/sbin/grub2-set-bootflag", st = {st_dev = 0, 
    st_ino = 18, st_nlink = 1, st_mode = 35309, st_uid = 0, st_gid = 0, 
    __pad0 = 0, st_rdev = 0, st_size = 10632, st_blksize = 0, st_blocks = 0, 
    st_atim = {tv_sec = 0, tv_nsec = 0}, st_mtim = {tv_sec = 1631200671, 
      tv_nsec = 0}, st_ctim = {tv_sec = 0, tv_nsec = 0}, __glibc_reserved = {
      0, 0, 0}}, idx = 17, type = 0x0, checksum = 0x0, cap = 0x0, flags = 0, 
  peer_file = 0x0, moved_path = false, moved_subpackage = false, items = {
    tqe_next = 0x714be0, tqe_prev = 0x6ffc60}}
(gdb) p *ri
$3 = {progname = 0x447d30 "/root/rpminspect/build/src/rpminspect", 
  cfgfiles = 0x40ca50, workdir = 0x40a6a0 "/root/tmp", 
  profiledir = 0x43cd70 "/usr/share/rpminspect/profiles/fedora", 
  worksubdir = 0x63b660 "/root/tmp/grub2-2.06.OCwzOw", commands = {
    diff = 0x40a460 "diff", diffstat = 0x40c410 "diffstat", 
    msgunfmt = 0x40c4d0 "msgunfmt", 
    desktop_file_validate = 0x40bf90 "desktop-file-validate", 
    annocheck = 0x40c050 "annocheck", abidiff = 0x40c110 "abidiff", 
    kmidiff = 0x40c1d0 "kmidiff"}, 
  vendor_data_dir = 0x40a160 "/usr/share/rpminspect", 
  licensedb = 0x40c650 "fedora.json", favor_release = FAVOR_NEWEST, 
  fileinfo_filename = 0x0, fileinfo = 0x0, caps = 0x0, caps_filename = 0x0, 
  rebaseable = 0x0, 
  rebaseable_filename = 0xc892a0 "/usr/share/rpminspect/rebaseable/fc35", 
  politics = 0x0, politics_filename = 0x0, security = 0xba4650, 
  security_filename = 0xba4670 "/usr/share/rpminspect/security/fc35", 
  security_initialized = false, icons = 0x0, icons_filename = 0x0, 
  kojihub = 0x43cdf0 "https://koji.fedoraproject.org/kojihub", 
  kojiursine = 0x43cea0 "https://kojipkgs.fedoraproject.org", 
  kojimbs = 0x43cf50 "https://kojipkgs.fedoraproject.org", 
  badwords = 0x40d760, vendor = 0x40d2c0 "Fedora Project", 
  buildhost_subdomain = 0x40de20, macrofiles = 0x0, 
  security_path_prefix = 0x40d6a0, header_file_extensions = 0x4463f0, 
  forbidden_path_prefixes = 0x446580, forbidden_path_suffixes = 0x4466a0, 
  forbidden_directories = 0x446740, bad_functions = 0x447ee0, arches = 0x0, 
  elf_path_include = 0x0, elf_path_exclude = 0x43d2b0, 
  manpage_path_include = 0x43e940, manpage_path_exclude = 0x0, 
  xml_path_include = 0x0, xml_path_exclude = 0x43fd40, 
  elf_path_include_pattern = 0x0, elf_path_exclude_pattern = 0x0, 
  manpage_path_include_pattern = 0x0, manpage_path_exclude_pattern = 0x0, 
  xml_path_include_pattern = 0x0, xml_path_exclude_pattern = 0x0, 
  desktop_entry_files_dir = 0x40a2e0 "/usr/share/applications", 
  bin_paths = 0x40b1e0, bin_owner = 0x40a760 "root", 
  bin_group = 0x40a820 "root", forbidden_owners = 0x4468a0, 
  forbidden_groups = 0x446900, shells = 0x40b5a0, size_threshold = 20, 
  lto_symbol_name_prefixes = 0x446970, specmatch = MATCH_FULL, 
  specprimary = PRIMARY_NAME, jvm = 0x446d30, annocheck = 0x446ab0, 
  pathmigration = 0x4473f0, pathmigration_excluded_paths = 0x4478a0, 
  products = 0x0, ignores = 0x40cfc0, forbidden_paths = 0x447920, 
  abidiff_suppression_file = 0x40b750 ".abignore", 
  abidiff_debuginfo_path = 0x447cc0 "/usr/lib/debug/", 
  abidiff_include_path = 0x447900 "/usr/include/", abidiff_extra_args = 0x0, 
  abi_security_threshold = 2, 
  kmidiff_suppression_file = 0x40aa60 ".abignore", 
  kmidiff_debuginfo_path = 0x40a3a0 "/usr/lib/debug/", 
  kmidiff_extra_args = 0x0, kernel_filenames = 0x447de0, kabi_dir = 0x0, 
  kabi_filename = 0x0, patch_ignore_list = 0x0, patch_file_threshold = 20, 
  patch_line_threshold = 5000, runpath_allowed_paths = 0x0, 
  runpath_allowed_origin_paths = 0x448370, 
  runpath_origin_prefix_trim = 0x4484a0, inspection_ignores = 0x4479b0, 
  expected_empty_rpms = 0x0, before = 0x0, 
  after = 0x4483f0 "grub2-2.06-5.fc35", tests = 18446744073709551615, 
  verbose = false, rebase_detection = true, threshold = RESULT_VERIFY, 
  worst_result = RESULT_BAD, product_release = 0xaebe70 "fc35", 
  buildtype = KOJI_BUILD_RPM, peers = 0x448470, header_cache = 0x63b020, 
  before_rel = 0x0, after_rel = 0x0, rebase_build = -1, 
  fortifiable = 0x573140, macros = 0xbe3660, results = 0x708290}
(gdb) 
```

and:

```
[root@fedora src]# file /root/tmp/grub2-2.06.OCwzOw/after/armv7hl/grub2-tools-minimal-2.06-5.fc35.armv7hl//usr/sbin/grub2-set-bootflag
/root/tmp/grub2-2.06.OCwzOw/after/armv7hl/grub2-tools-minimal-2.06-5.fc35.armv7hl//usr/sbin/grub2-set-bootflag: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=c7db0c75741eddd98679943eec069dd9fa8d7927, for GNU/Linux 3.2.0, stripped
[root@fedora src]# 
```

(This also occurs in rawhide and fc34.)

**Comment by dcantrell** [comment]
I can fix this up tomorrow.
